disable_existing_loggers: true
formatters:
    dashed:
        class: Monolog\Formatter\LineFormatter
        format: "%datetime%-%channel%.%level_name% - %message%\n"
handlers:
    debug:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/debug.log
    system:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/system.log
    exception:
        class: Monolog\Handler\StreamHandler
        level: EMERGENCY
        formatter: dashed
        stream: ${LOCAL_ROOT}/log/exception.log
    setup_hndl:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/setup.log
    odoo_api:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/odoo.log
    sql_hndl:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/sql.log
loggers:
    main:
        handlers: [debug, system, exception]
    setup:
        handlers: [setup_hndl]
    odoo:
        handlers: [odoo_api]
    sql:
        handlers: [sql_hndl]