disable_existing_loggers: true
formatters:
    dashed:
        class: Monolog\Formatter\LineFormatter
        format: "%datetime%-%channel%.%level_name% - %message%\n"
handlers:
    debug:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/cascade_debug.log
    system:
        class: Monolog\Handler\StreamHandler
        level: INFO
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/cascade_system.log
    exception:
        class: Monolog\Handler\StreamHandler
        level: EMERGENCY
        formatter: dashed
        stream: ${LOCAL_ROOT}/log/cascade_exception.log
    setup_hndl:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/cascade_setup.log
    odoo_api:
        class: Monolog\Handler\StreamHandler
        level: DEBUG
        formatter: dashed
        stream: ${LOCAL_ROOT}/var/log/cascade_odoo.log
loggers:
    main:
        handlers: [debug, system, exception]
    setup:
        handlers: [setup_hndl]
    odoo:
        handlers: [odoo_api]